---

- hosts: local
  become: yes
  tasks:

    - name: Update & Upgrade
      pacman:
        update_cache: yes
        upgrade: yes

    - name: Install termite
      pacman:
        name: termite
        state: present

    - name: Install php
      pacman:
        name: php
        state: present

    - name: Copy i3 config
      copy:
        src: files/i3/config
        dest: /home/nmalacarne/.i3/config 

    - name: Copy i3 status config
      copy:
        src: files/i3/i3status.conf
        dest: /etc/i3status.conf
      become_user: nmalacarne

    - name: Copy i3 sensible terminal
      copy:
        src: files/i3/i3-sensible-terminal
        dest: /usr/bin/i3-sensible-terminal

    - name: Copy bashrc
      copy:
        src: files/bash/bashrc
        dest: /home/nmalacarne/.bashrc
      become_user: nmalacarne

    - name: Copy bash profile
      copy:
        src: files/bash/profile
        dest: /home/nmalacarne/.profile
      become_user: nmalacarne

    - name: Copy Xresources
      copy:
        src: files/X/resources
        dest: /home/nmalacarne/.Xresources

    - name: Create vim directory
      file:
        path: /home/nmalacarne/.vim
        state: directory
      become_user: nmalacarne

    - name: Create vim autoload directory
      file:
        path: /home/nmalacarne/.vim/autoload
      become_user: nmalacarne

    - name: Check if vim plug is installed
      stat:
        path: /home/nmalacarne/.vim/autoload/plug.vim
      register: vim_plug_installed

    - name: Install vim plug
      get_url:         
        url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
        dest: /home/nmalacarne/.vim/autoload/plug.vim
      when: not vim_plug_installed.stat.exists

    - name: Copy vim config
      copy:
        src: files/vim/vimrc
        dest: /home/nmalacarne/.vimrc
      become_user: nmalacarne

    - name: Copy conky config
      copy:
        src: files/conky/start_conky_maia
        dest: /usr/bin/start_conky_maia
      become_user: nmalacarne

    - name: Create termite config directory
      file:
        path: /home/nmalacarne/.config/termite
        state: directory

    - name: Check termite config
      stat:
        path: /home/nmalacarne/.config/termite/config
      register: termite_config_created

    - name: Setup termite theme
      get_url:
        url: https://raw.githubusercontent.com/arcticicestudio/nord-termite/develop/src/config
        dest: /home/nmalacarne/.config/termite
      when: not termite_config_created.stat.exists

    - name: Setup bash prompt
      get_url:
        url: https://raw.githubusercontent.com/arcticicestudio/igloo/develop/snowblocks/bash/core/prompt
        dest: /home/nmalacarne/.config/bash_prompt

    - name: Setup directory colors
      get_url:
        url: https://raw.githubusercontent.com/arcticicestudio/nord-dircolors/develop/src/dir_colors
        dest: /home/nmalacarne/.dir_colors

    - name: Check PHPStorm
      stat:
        path: /home/nmalacarne/PhpStorm-182.3684.42
      register: phpstorm_installed

    - name: Download PHPStorm
      get_url:
        url: https://download.jetbrains.com/webide/PhpStorm-2018.2.tar.gz
        dest: /home/nmalacarne/Downloads
      when: not phpstorm_installed.stat.exists
      become_user: nmalacarne

    - name: Unzip PHPStorm
      unarchive:
        src: /home/nmalacarne/Downloads/PhpStorm-2018.2.tar.gz
        dest: /home/nmalacarne
      when: not phpstorm_installed.stat.exists
      become_user: nmalacarne
