call plug#begin('~/.vim/plugged')

Plug 'scrooloose/nerdtree'
Plug 'kien/ctrlp.vim'
Plug 'editorconfig/editorconfig-vim'
Plug 'StanAngeloff/php.vim'

call plug#end()

set number
set showmode
set nobackup
set noswapfile
set nocompatible

nmap <C-h> <C-w>h
nmap <C-j> <C-w>j
nmap <C-k> <C-w>k
nmap <C-l> <C-w>l

nmap <C-b> :NERDTreeToggle<cr>
nmap <leader>cp :CtrlP<cr>
