call plug#begin('~/.vim/plugged')

Plug 'scrooloose/nerdtree'
Plug 'kien/ctrlp.vim'
Plug 'editorconfig/editorconfig-vim'
Plug 'StanAngeloff/php.vim'
Plug 'arcticicestudio/nord-vim'

call plug#end()

set number
set showmode
set nobackup
set noswapfile
set nocompatible
set tabstop=8
set shiftwidth=8
set expandtab

autocmd FileType js setlocal shiftwidth=2 tabstop=2
autocmd FileType yml setlocal shiftwidth=2 tabstop=2
autocmd FileType php setlocal shiftwidth=4 tabstop=4

colorscheme nord

nmap <C-h> <C-w>h
nmap <C-j> <C-w>j
nmap <C-k> <C-w>k
nmap <C-l> <C-w>l

nmap <C-b> :NERDTreeToggle<cr>
nmap <leader>cp :CtrlP<cr>
